version: '2'

services:
  mariadb:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_DATABASE=ove
      - MYSQL_USER=ove
      - MYSQL_PASSWORD=ove

  http:
    build:
      context: ../..
      dockerfile: ./docker/api/Dockerfile.http
    environment:
      - http_proxy
      - SERVICE=video
      - REDIS=redis://redis:6379
      - RACK_DB_NAME=ove
      - RACK_DB_USER=ove
      - RACK_DB_PASS=ove
      - RACK_DB_HOST=mariadb
      - RACK_ENV=production
    volumes:
      - video:/video

  redis:
  	image: redis

volumes:
  video: 
