global:
    # This variable defines a secret key that allows nodes to validate that communication is valid.
    secret_key: "LjHX7XqiC52vC6tl1e1v365hmIW8Sbdr6U07vw3lWIDWWNp44VtvHkC5HjqD16p"

ingest:
    # This allows us to offload rendering onto another machine, provided this machine can access
    #  this IP address. We use the above secret key to ensure security. 
    public_uri: http://video-ingest-revprox.insanityradio.com

share:
    facebook:
        app_access_token: secret
        app_id: 312258302764699
        app_secret: 122b3498ed280706cebfe7998356e4a7

render:
    scratch: /video
    expiry: 2592000

