global:
	# This variable defines a secret key that allows nodes to validate that communication is valid.
	secret_key: "LjHX7XqiC52vC6tl1e1v365hmIW8Sbdr6U07vw3lWIDWWNp44VtvHkC5HjqD16p"

ingest:
	sources:
		video:
			root: /video
import:
