source 'https://rubygems.org'

gem 'fakeredis'
gem 'falcon'
gem 'mysql2'
gem 'redis'
gem 'redis-namespace'
gem 'reek'
gem 'rspec'
gem 'rubocop'
gem 'sinatra'
gem 'sinatra-activerecord'
gem 'sinatra-contrib'
