source 'https://rubygems.org'

gem 'fakeredis'
gem 'falcon'
gem 'mysql2'
gem 'rake'
gem 'redis', '< 4.0.0'
gem 'redis-namespace'
gem 'reek'
gem 'resque', '1.27.4'
gem 'resque-status', '0.5.0'
gem 'rspec'
gem 'rubocop'
gem 'sinatra'
gem 'sinatra-activerecord'
gem 'sinatra-contrib'
