version: '2'

services:
  capture:
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile.capture
    environment:
      - http_proxy
      - PULL_URL=rtmp://10.32.0.222:1935/falcon/video

    restart: always
    volumes: 
      - video:/video

  http:
    build:
      context: ../..
      dockerfile: ./docker/ingest/Dockerfile.http
    environment:
      - http_proxy
      - SERVICE=video
      - REDIS=redis://redis:6379
    restart: always
    volumes:
      - video:/video
  index:
    build:
      context: ../..
      dockerfile: ./docker/ingest/Dockerfile.index
    environment:
      - http_proxy
      - SERVICE=video
      - REDIS=redis://redis:6379
    restart: always
    volumes:
      - video:/video

  nginx:
    image: nginx:mainline
    depends_on:
      - http
    ports:
      - '1965:80'
    restart: always
    volumes:
      - ./nginx_dist.conf:/etc/nginx/nginx.conf
      - video:/video

#  ffmpeg:
#    image: jrottenberg/ffmpeg
#    command: -re -stream_loop -1 -i /video.ts -c:v copy -c:a copy -bsf:a aac_adtstoasc -f flv rtmp://capture/video/video
#    volumes:
#      - ./dummy.ts:/video.ts

  redis:
    restart: always
    image: redis

volumes:
  video: 
