import Model from './Model';
import CoreVideo from './CoreVideo';

/**
 * Import is a model that represents an import object, as generated by the server.
 *
 * Hence, it is immutable. 
 */
export default class CoreImport extends Model {

	constructor (data, serviceName) {
		super(data);

		this.attr_reader('uuid');
		this.attr_reader('title');
		this.attr_reader('videos', CoreVideo, true);
		this.attr_reader('created_by');
	}

}