import Model from './Model';

/**
 * Import is a model that represents an import object, as generated by the server.
 *
 * Hence, it is immutable. 
 */
export default class CoreVideo extends Model {

	constructor (data, serviceName) {
		super(data);

		this.attr_reader('id');
		this.attr_reader('created_by');
		this.attr_reader('type');
		this.attr_reader('configuration');
		this.attr_reader('queued');
		this.attr_reader('rendered');
	}

	getDownloadPath () {
		return this.getBasePath() + '/download.mp4';
	}

	getBasePath () {
		return '/api/import/todo/video/' + this.id;
	}

}