import Model from './Model';

/**
 * Import is a model that represents an import object, as generated by the server.
 *
 * Hence, it is immutable. 
 */
export default class Import extends Model {

	constructor (data, serviceName) {
		data['service_name'] = serviceName;
		super(data);

		this.attr_reader('uuid');
		this.attr_reader('start_time');
		this.attr_reader('end_time');
		this.attr_reader('real_start_time');
		this.attr_reader('real_end_time');
		this.attr_reader('length');
		this.attr_reader('start_offset');
		this.attr_reader('expiry');
		this.attr_reader('service_name');
	}

	getPreviewPath () {
		return this.getBasePath() + '/preview.m3u8';
	}

	getBasePath () {
		return '/api/ingest/' + this.service_name + '/import/' + this.uuid;
	}

}