import Model from './Model';

/**
 * Import is a model that represents an import object, as generated by the server.
 *
 * Hence, it is immutable. 
 */
export default class Platform extends Model {
	constructor (data, serviceName) {
		super(data);

		this.attr_reader('id');
		this.attr_reader('name');
		this.attr_reader('configuration');
		this.attr_reader('platform_type');
		this.attr_reader('default_share_text');
	}

	get icon () {
		let icons = {
			facebook: ['fab', 'facebook-f'],
			instagram: ['fab', 'instagram'],
			twitter: ['fab', 'twitter'],
			youtube: ['fab', 'youtube']
		}

		return icons[this.platform_type] || this.platform_type;
	}
}