import Model from './Model';

/**
 * Import is a model that represents an import object, as generated by the server.
 *
 * Hence, it is immutable. 
 */
export default class Slate extends Model {
	constructor (data, serviceName) {
		super(data);

		this.attr_reader('id');
		this.attr_reader('name');
	}

	getThumbnailPath () {
		return this.getBasePath() + '/thumbnail.jpg';
	}

	getPath () {
		return this.getBasePath() + '/download.mp4';
	}

	getBasePath () {
		return '/api/slates/' + this.id;
	}
}